server:
  host: localhost
  port: 8080
  env: development
postgresql:
  host: localhost
  port: 5432
  username: username
  password: password
  database: postgres
rmq:
  dsn: amqp://nsv_rmq_user:secure_password@localhost:5672/
  queue_name: cms_service
security:
  auth_cookie_prefix: nsv-auth
  better_auth_secret: ZaijXVU...
